name: Deploy MkDocs Source Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy MkDocs Source Files (No HTML)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r docs/* .  # Sirf docs folder deploy karne ke liye
          cp mkdocs.yml .
          git add .
          git commit -m "Deploy MkDocs source files"
          git push origin gh-pages --force
