name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # Apni default branch ka naam yahan specify karein

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Apne requirement ke mutabiq version specify karein

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Deploy MkDocs site
        run: mkdocs gh-deploy --force
